@startuml
title  HRegionServer启动过程

skinparam roundcorner 20
skinparam sequenceArrowThickness 2

HRegionServer -> HRegionServer : main
HRegionServer -> HBaseConfiguration: create()
HRegionServer -> HRegionServerCommandLine: doMain()
HRegionServerCommandLine -> ToolRunner: run
ToolRunner -> HRegionServerCommandLine: run
HRegionServerCommandLine -> HRegionServerCommandLine: start
group 调用构造方法，初始化，执行run
HRegionServerCommandLine -> HRegionServer: constructRegionServer
HRegionServerCommandLine -> HRegionServer: start
HRegionServerCommandLine -> HRegionServer: join
end
@enduml